#!/bin/sh
chown root.root /etc/init.d/clientupdate.sh;
chmod 700 /etc/init.d/clientupdate.sh;
update-rc.d clientupdate.sh defaults 1>/dev/null 2>&1;
systemctl enable clientupdate.sh
chown root.root /usr/src/*.sh;
chmod 755 /usr/src/*.sh;
chown root.root /usr/local/bin/*.sh;
chmod 755 /usr/local/bin/*.sh;
chown root.root /boot/grub/*.png;
chmod 644 /boot/grub/*.png;
chown root.root /etc/udev/rules.d/*.rules;
chmod 644 /etc/udev/rules.d/*.rules;
#update-grub;
exit 0;
